let drinks = [
  {
    name: "water",
    hotorcold: ["cold", "hot"],
    type: "water",
    price: 2,
    img: "https://images.absolutdrinks.com/drink-images/Raw/Absolut/1024d9d2-0d05-41a3-b515-8dbb5e13d2b3.jpg",
    healthy: true,
  },
  {
    name: "sparkling water",
    hotorcold: ["cold", "hot"],
    type: "water",
    price: 2,
    img: "https://tasteofartisan.com/wp-content/uploads/2019/03/Homemade-carbonated-water-in-a-glass.jpg",
    healthy: true,
  },
  {
    name: "coke",
    hotorcold: "cold",
    type: "soda",
    price: 4,
    img: "https://cdn.shopify.com/s/files/1/2679/6864/products/grocery-coca-cola-classic-canned-coke-products-12-oz-can-14052198088757_1024x1024.png?v=1611222385",
    healthy: false,
  },
  {
    name: "sprite",
    hotorcold: "cold",
    type: "soda",
    price: 4,
    img: "https://scene7.samsclub.com/is/image/samsclub/0004900007727_B?wid=400&hei=400",
    healthy: false,
  },
  {
    name: "orange juice",
    hotorcold: "cold",
    type: "juice",
    price: 6,
    img: "https://salimaskitchen.com/wp-content/uploads/2022/01/Fresh-Squeezed-Orange-Juice-Salimas-Kitchen-20.jpg",
    healthy: true,
  },
  {
    name: "apple juice",
    hotorcold: "cold",
    type: "juice",
    price: 6,
    img: "https://i0.wp.com/nycstreetgrill.com/wp-content/uploads/2019/08/glass-of-apple-juice-with-slices-of-red-apple-vector-18547427-copy.jpg?fit=1000%2C1004&ssl=1",
    healthy: true,
  },
  {
    name: "coffee",
    hotorcold: ["hot", "cold"],
    type: "coffee",
    price: 8,
    img: "https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    healthy: false,
  },
  {
    name: "ginger tea",
    hotorcold: ["hot", "cold"],
    type: "tea",
    price: 6,
    img: "https://detoxinista.com/wp-content/uploads/2020/10/ginger-tea-recipe.jpg",
    healthy: true,
  },
];

export { drinks };
